import React from 'react';
import { cn } from 'tailwind-variants';
import { lexend } from '~/lib/fonts';
import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en" className="h-full bg-surface text-on-surface antialiased">
      <body className={cn('font-lexend flex min-h-full flex-col', lexend.variable)}>{children}</body>
    </html>
  );
};

export default RootLayout;
